[package]
name = "my_parser_kma_lol1337"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "gud parser"

[dependencies]
anyhow = "1.0.100"
peg = "0.8.5"
pest = "2.8.3"
pest_derive = "2.8.3"
